programs:
    1:
      dapp: "nft_marketplace"
      repo: "non-fungible-token"
      optDownloadUrl: "https://github.com/gear-dapps/non-fungible-token/releases/download/0.1.0/nft_marketplace-0.1.0.opt.wasm"
      metaDownloadUrl: "https://github.com/gear-dapps/non-fungible-token/releases/download/0.1.0/nft_marketplace-0.1.0.meta.wasm"
      acc: "alice"
      payload:
        adminId: '0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d'
        treasuryId: '0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d'
        treasuryFee: "1"

    2:
      dapp: "nft"
      repo: "non-fungible-token"
      optDownloadUrl: "https://github.com/gear-dapps/non-fungible-token/releases/download/0.1.0/nft-0.1.0.opt.wasm"
      metaDownloadUrl: "https://github.com/gear-dapps/non-fungible-token/releases/download/0.1.0/nft-0.1.0.meta.wasm"
      acc: "alice"
      payload:
        name: "test"
        symbol: "test"
        baseUrl: "test"
        royalties: NULL

    3:
      dapp: "#nft"
      repo: "non-fungible-token"
      optDownloadUrl: "https://github.com/gear-dapps/non-fungible-token/releases/download/0.1.0/nft-0.1.0.opt.wasm"
      metaDownloadUrl: "https://github.com/gear-dapps/non-fungible-token/releases/download/0.1.0/nft-0.1.0.meta.wasm"
      acc: "alice"
      payload:
        name: "test"
        symbol: "test"
        baseUrl: "test"
        royalties: NULL

    4:
      dapp: "lottery"
      repo: "lottery"
      optDownloadUrl: "https://github.com/gear-dapps/lottery/releases/download/0.1.0/lottery-0.1.0.opt.wasm"
      metaDownloadUrl: "https://github.com/gear-dapps/lottery/releases/download/0.1.0/lottery-0.1.0.meta.wasm"
      acc: "alice"
      payload: "0x00"

    5:
      dapp: "dutch-auction"
      repo: "dutch-auction"
      optDownloadUrl: ""
      metaDownloadUrl: ""
      acc: "alice"
      payload: "0x00"

    6:
      dapp: "escrow"
      repo: "escrow"
      optDownloadUrl: ""
      metaDownloadUrl: ""
      acc: "alice"
      payload: ""

    7:
      dapp: "supply-chain"
      repo: "supply-chain"
      optDownloadUrl: ""
      metaDownloadUrl: ""
      acc: "alice"
      payload: ""

workflow:
    - command: uploadProgram
      program: 1

    - command: uploadProgram
      program: 3

    - command: sendMessage
      program: 1
      acc: "alice"
      payload:
        AddNftContract: 3

    - command: uploadProgram
      program: 2

