version: '3'

services:
  pg_data_storage:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /home/ec2/data-storage/pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  data_storage:
    image: mithriy/gear-data-storage:nightly
    restart: always
    depends_on:
      - pg_data_storage
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - CLIENT_ID=${KAFKA_CLIENT_ID}
      - GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
