name: production.frontend-CD

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy-frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build frontend
        run: |
          yarn install
          yarn build:frontend
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_NODE_ADDRESS: ${{ secrets.WS_PROVIDER_TESTNET }}
          REACT_APP_WASM_COMPILER_URL: ${{ secrets.REACT_APP_WASM_COMPILER_URL }}
          REACT_APP_DEFAULT_NODES_URL: ${{ secrets.REACT_APP_DEFAULT_NODES_URL }}
          REACT_APP_HCAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_HCAPTCHA_SITE_KEY }}
          REACT_APP_RRT: ''

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible/tasks/frontend
          playbook: frontend.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.PROD_HOST}}
          requirements: ../../galaxy-requirements.yml
