name: 'Vara.Eth Idea Release'

on:
  push:
    branches: ['main']
    paths:
      - idea/vara-eth/**
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Service to release
        options:
          - frontend
          - indexer
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.frontend.outputs.changed }}
      indexer: ${{ steps.indexer.outputs.changed }}
    steps:
      - uses: action/checkout@v6

      - name: Check frontend
        id: frontend
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changed:
              - idea/vara-eth/frontend/src/**
              - idea/vara-eth/frontend/package.json

      - name: Check indexer
        id: indexer
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changed:
              - idea/vara-eth/indexer/src/**
              - idea/vara-eth/indexer/package.json

  set-env-tag:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get_env.outputs.environment }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get environment
        id: get_env
        run: echo "environment=vara-eth-idea-staging" >> $GITHUB_OUTPUT

  build-frontend-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check if should be built
        id: check
        uses: './.github/actions/should-be-built'
        with:
          patterns: 'frontend,all'
          input: ${{ github.event.inputs.service }}
          event_name: ${{ github.event_name }}

      - name: Log in to the github container registry
        if: ${{ steps.check.outputs.ok == 'true' }}
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "vara-eth-idea-frontend" Docker image
        if: ${{ steps.check.outputs.ok == 'true' }}
        uses: docker/build-push-action@master
        with:
          file: idea/vara-eth/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-vara-eth-idea-frontend:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-vara-eth-idea-frontend:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}
          build-args: |
            VITE_WALLET_CONNECT_PROJECT_ID=${{ secrets.VITE_WALLET_CONNECT_PROJECT_ID }}
            VITE_VARA_ETH_NODE_ADDRESS=${{ secrets.VITE_VARA_ETH_NODE_ADDRESS }}
            VITE_ETH_NODE_ADDRESS=${{ secrets.VITE_ETH_NODE_ADDRESS }}
            VITE_ROUTER_CONTRACT_ADDRESS=${{ secrets.VITE_ROUTER_CONTRACT_ADDRESS }}

  build-indexer-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs.indexer == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check if should be built
        id: check
        uses: './.github/actions/should-be-built'
        with:
          patterns: 'squid,all,backend'
          input: ${{ github.event.inputs.service }}
          event_name: ${{ github.event_name }}

      - name: Log in to the github container registry
        if: ${{ steps.check.outputs.ok == 'true' }}
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "vara-eth-idea-squid" image
        if: ${{ steps.check.outputs.ok == 'true' }}
        uses: docker/build-push-action@master
        with:
          file: idea/vara-eth/indexer/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-vara-eth-idea-squid:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-vara-eth-idea-squid:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}

  deploy-to-k8s:
    needs:
      [
        build-frontend-image,
        build-indexer-image,
      ]
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get deployment variables
        id: deployment_vars
        run: |
          echo "namespace=dev-1" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" != "workflow_dispatch" || "${{ github.event.inputs.service }}" == "all" ]; then
            echo "deployments=vara-eth-indexer vara-eth-frontend" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.service }}" == "frontend" ]; then
            echo "deployments=vara-eth-frontend" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.service }}" == "indexer" ]; then
            echo "deployments=vara-eth-indexer" >> $GITHUB_OUTPUT
          else
            echo "deployments=" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment ${{ steps.deployment_vars.outputs.deployments }} -n ${{ steps.deployment_vars.outputs.namespace }}
