name: staging.events-listener-CD

on:
  push:
    branches: [master, do-events-listener-deploy]
    paths:
      - website/events-listener/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-events-listener-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push events-listener docker
        id: events_listener_docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/events-listener/Dockerfile
          push: true
          tags: mithriy/gear-event-listener:nightly

  Deploy:
    runs-on: ubuntu-latest
    needs: build-events-listener-docker
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
          WS_PROVIDER_TESTNET: ${{ secrets.WS_PROVIDER_TESTNET }}
          KAFKA_CLIENT_ID_TESTNET: ${{ secrets.EVENTS_LISTENER_TESTNET_KAFKA_CLIENT_ID }}
          WS_PROVIDER_WRSH: ${{ secrets.WS_PROVIDER_WRSH }}
          KAFKA_CLIENT_ID_WRSH: ${{ secrets.EVENTS_LISTENER_WRSH_KAFKA_CLIENT_ID }}

        with:
          directory: ./ansible/tasks/events-listener
          playbook: events-listener.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ secrets.STAGING_HOST }}
          requirements: ../../galaxy-requirements.yml
