name: staging.kafka-CD

on:
  push:
    branches: [master, do-event-listener]
    paths:
      - ansible/tasks/kafka/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_HOST_NAME: ${{ secrets.KAFKA_HOST_NAME }}

        with:
          directory: ./ansible/tasks/kafka
          playbook: kafka.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{secrets.STAGING_HOST}}
          requirements: ../../galaxy-requirements.yml
