name: staging.test-balance-CD

on:
  push:
    branches: [master, do-event-listener]
    paths:
      - website/test-balance/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/test-balance/Dockerfile
          push: true
          tags: mithriy/gear-test-balance:nightly

  Deploy:
    needs: Build-backend-docker
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_BROKERS: ${{secrets.KAFKA_BROKERS}}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_BALANCE_DB_NAME }}
          DB_USER: ${{ secrets.TEST_BALANCE_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_BALANCE_DB_PASSWORD }}
          KAFKA_CLIENT_ID_WRSH: ${{ secrets.TEST_BALANCE_KAFKA_CLIENT_ID_WRSH }}
          KAFKA_GROUP_ID_WRSH: ${{ secrets.TEST_BALANCE_KAFKA_GROUP_ID_WRSH }}
          WS_PROVIDER_WRSH: ${{ secrets.TEST_BALANCE_WS_PROVIDER_WRSH }}
          ROOT_ACCOUNT_SEED_WRSH: ${{ secrets.TEST_BALANCE_ROOT_ACCOUNT_SEED_WRSH }}
          TEST_ACCOUNT_SEED: ${{ secrets.TEST_BALANCE_ACCOUNT_SEED }}
          TEST_ACCOUNT_BALANCE_WRSH: ${{ secrets.TEST_BALANCE_ACCOUNT_BALANCE_WRSH }}
          TEST_BALANCE_VALUE_WRSH: ${{ secrets.TEST_BALANCE_VALUE_WRSH }}

        with:
          # Required, playbook filepath
          directory: ./ansible/tasks/test-balance
          playbook: test-balance.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.STAGING_HOST}}
          requirements: ../../galaxy-requirements.yml
