name: staging.api-gateway-CD

on:
  push:
    branches: [master, do-extrinsic-block]
    paths:
      - website/api-gateway/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-api-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build api-gateway
        run: |
          yarn workspace @gear-js/api-gateway install
          yarn build:apiGateway

      - name: Build and push docker image
        id: api_backend_docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/api-gateway/Dockerfile
          push: true
          tags: mithriy/gear-api-gateway:nightly

  Deploy:
    runs-on: ubuntu-latest
    needs: build-api-backend-docker
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_CLIENT_ID: ${{ secrets.API_GATEWAY_KAFKA_CLIENT_ID }}
          KAFKA_GROUP_ID: ${{ secrets.API_GATEWAY_KAFKA_GROUP_ID }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}

        with:
          directory: ./ansible/tasks/api-gateway
          playbook: api-gateway.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{secrets.STAGING_HOST}}
          requirements: ../../galaxy-requirements.yml
